// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qiazkluyvucsgrztceda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpYXprbHV5dnVjc2dyenRjZWRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NDU2NDEsImV4cCI6MjA3MzAyMTY0MX0.SgMwwoKS76OVMGfFJFTPIbwjA6BA8_kl_1X680lBBZg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});